package app

// resourceDescriptions is the ":" resource search's preview-pane copy, one
// paragraph per registry.Resource.Key() — plain OCI documentation-style
// descriptions, not tied to anything fetched at runtime. Keyed by Key()
// rather than a Resource method so adding one doesn't touch every resource
// file in internal/registry, same idea as resourceCategories.
var resourceDescriptions = map[string]string{
	"instance":               "An instance is a compute host. Choose between virtual machines (VMs) and bare metal instances. The image that you use to launch an instance determines its operating system and other software.",
	"vcn":                    "Virtual Cloud Networks (VCNs) are private virtual networks you set up in Oracle Cloud Infrastructure. You can attach gateways, route tables, and security lists to specify routing and security rules.",
	"subnet":                 "A subnet is a subdivision of a VCN, consisting of a contiguous range of IP addresses that don't overlap with the VCN's other subnets. You mark a subnet public or private, which controls whether its VNICs can have a public IP address.",
	"route-table":            "Traffic within the VCN is handled by the VCN's local routing by default. Intra-VCN routing allows you more control over routing between subnets.",
	"security-list":          "A security list acts as a virtual firewall, with ingress and egress rules that specify the types of traffic allowed in and out of the VNICs it's associated with. Unlike an NSG, a security list applies to every VNIC in the subnets it's attached to.",
	"nsg":                    "A network security group consists of a set of VNICs and a set of security rules that apply to those VNICs. For example: you create a network security group for all the instances in the VCN that have the same security posture. For comparison, a VCN security list consists of a set of security rules that apply to all the VNICs in the subnets that the security list is associated with.",
	"drg":                    "Dynamic routing gateways (DRGs) are optional virtual routers that you can add to your VCN. They provide a path for private network traffic between your VCN and on-premises network.",
	"drg-attachment":         "A DRG attachment connects a DRG to a network — a VCN, an on-premises network over IPSec or FastConnect, or a remote peering connection — so traffic between them can flow through the DRG. A single DRG can have many attachments.",
	"drg-route-table":        "A DRG route table manages routing within the DRG. Two route tables are automatically created for a new DRG, and you can create more route tables as needed. You can configure all resources of a certain type to use the same route table.",
	"drg-route-distribution": "A DRG route distribution controls which routes get imported into a DRG route table from its attachments, or exported out to them — the mechanism that decides which networks a DRG actually shares routes between.",
	"lb":                     "The load balancer service provides a reverse proxy solution that hides the IP of the client from backend application server and vice versa. It is capable of performing advanced layer 7 (HTTP/HTTPS), layer 4 (TCP) load balancing and SSL offloading.",
	"lb-listener":            "A listener checks for incoming traffic on a load balancer's IP address, using the protocol and port you configure, and routes it to the backend set (or, via a routing policy, one of several) it's assigned. Only browsable scoped to one load balancer (Enter on a lb row).",
	"lb-backend-set":         "A backend set is a logical grouping of backend servers that receive traffic from a listener, along with the load balancing policy and health check that manage them. Only browsable scoped to one load balancer (Enter on a lb row).",
	"lb-routing-policy":      "A routing policy is an ordered list of rules that route a listener's traffic to different backend sets based on the request — the modern replacement for a listener's older, single path route set. Only browsable scoped to one load balancer (Enter on a lb row).",
	"lb-rule-set":            "A rule set is a named, reusable collection of actions (adding, altering, or removing HTTP headers, for example) that one or more listeners can apply to their traffic. Only browsable scoped to one load balancer (Enter on a lb row).",
	"lb-path-route-set":      "A path route set is a named collection of path-based routing rules, now deprecated in favor of routing policies but still supported on existing listeners that use one. Only browsable scoped to one load balancer (Enter on a lb row).",
	"lb-certificate":         "A certificate bundle holds the SSL/TLS certificate (and any CA/intermediate certificate) a load balancer presents for SSL termination or backend re-encryption. Only browsable scoped to one load balancer (Enter on a lb row).",
	"lb-hostname":            "A hostname resource is a virtual hostname a listener can match incoming requests against, letting one load balancer route traffic for several different domain names. Only browsable scoped to one load balancer (Enter on a lb row).",
	"gateway":                "Every Internet, NAT, and Service Gateway in the compartment (and VCN, if scoped), merged into one list — pick this to see them all at once instead of one type at a time.",
	"igw":                    "An internet gateway lets traffic travel between a VCN's public subnets and the internet. A VCN needs one only if it has a public subnet, and traffic to/from that subnet is controlled by the VCN's route tables and security rules, not the gateway itself.",
	"nat-gateway":            "A NAT gateway gives instances in a private subnet outbound-only access to the internet — they can initiate connections out, but nothing from the internet can initiate a connection in. Unlike an internet gateway, it never gives instances a public IP.",
	"service-gateway":        "A service gateway lets instances in a VCN privately access Oracle services (like Object Storage) over the Oracle network fabric instead of the public internet, without needing internet gateways, NAT gateways, or public IPs.",
	"oke":                    "Container Engine for Kubernetes (OKE) is a managed Kubernetes service. You describe the compute resources your workloads need, and OKE provisions and operates the underlying Kubernetes cluster for you on Oracle Cloud Infrastructure.",
	"oke-node-pool":          "A node pool is a subset of an OKE cluster's worker nodes that share the same shape, image, and configuration. A cluster can have several pools with different node shapes for different workloads. Only browsable scoped to one cluster (Enter on an oke row).",
	"file-system":            "File Storage Service (FSS) provides a durable, scalable NFS file system for use with any bare metal, virtual machine, or container instance. A file system's storage capacity grows and shrinks automatically as you add or remove data.",
	"bucket":                 "A bucket is a logical container for storing objects in Object Storage. It's a flat namespace of key-value pairs — object name to data — with no folder hierarchy of its own, though object names with slashes can be displayed as one.",
	"db-system":              "A DB system is the compute and storage foundation for one or more Oracle databases — virtual machine, bare metal, or Exadata — that OCI provisions, patches, and backs up as a unit.",
	"adb":                    "Autonomous Database is a fully managed database that automates provisioning, tuning, patching, and backup. It runs OLTP, data warehouse, JSON, or mixed workloads without you having to manage the underlying infrastructure.",
	"mysql":                  "MySQL HeatWave is a fully managed MySQL database service. A DB system can run standalone or highly available (three instances), and optionally attach a HeatWave cluster — in-memory analytics nodes that accelerate queries and lakehouse workloads without moving data out of MySQL. Enter shows the connection endpoints; \"g\" lists the HeatWave nodes.",
	"exadata":                "An Exadata VM cluster is a set of virtual machines on Exadata Cloud Infrastructure that share the underlying Exadata hardware and provide the compute layer for one or more DB systems running on it.",
	"exascale":               "Exadata Database Service on Exascale Infrastructure pools compute and storage across a fleet of Exadata hardware, letting VM clusters scale compute and storage independently and elastically instead of in fixed increments.",
	"compartment":            "A compartment is a logical container for organizing and isolating your cloud resources — for billing, access control via IAM policies, and management. Every resource belongs to exactly one compartment.",
	"recent":                 "Every resource created in the last 3 days, across every kind, merged into one list sorted newest first — a quick way to see what's new without checking each resource kind by hand. Based on creation time only, not later edits.",
}
